redis:
  image: redis
  container_name: "red"
  ports:
    - "6379:6379"


#redis-proxy:
#  #image: openjdk:8-jre
#  build: .
#  container_name: "redis-proxy"
#  ports:
#    - "8080:8080"  
#  links:
#    - redis:red  
#  volumes:
#      - .:/app
#  environment:
#    - REDIS_HOST=red
#    - REDIS_PORT=6379
#  entrypoint: ["make", "run"]
#  entrypoint: ["java", "-cp", "bin:lib/jedis-2.9.0.jar:lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar:lib/commons-pool2-2.6.0.jar::.", "Main"]
